@echo off
echo Training YOLOv8...
python %~dp0train_yolo.py --model yolov8n.pt --epochs 50 --device cpu
echo Training YOLOv5...
python %~dp0train_yolo.py --model yolov5su.pt --epochs 50 --device cpu
echo Training EfficientDet...
python %~dp0train_yolo.py --model efficientdet_d0 --epochs 50 --device cpu
